#!groovy
pipeline {

  options {
    ansiColor('xterm')
  }

  agent {
    kubernetes {
      yamlFile './consumer-app/builder.yaml'
    }
  }

  stages {

    stage('Kaniko Build & Push Image') {
      steps {
        container('kaniko') {
          script {
            sh '''
            /kaniko/executor --dockerfile `pwd`/consumer-app/Dockerfile \
                             --context `pwd` \
                             --destination=guysaar8/consumer:1.0.${BUILD_NUMBER}
            '''
          }
        }
      }
    }
      

   }   
}
